
openapi: 3.0.0
info:
  title: HRM Backend API
  version: '1.0'
servers:
  - url: http://localhost:4000
paths:
  /api/auth/register:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string }
                password: { type: string }
                role: { type: string }
      responses:
        '201': { description: Created }
  /api/auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200': { description: OK }
  /api/employees:
    get:
      summary: List employees
      security:
        - bearerAuth: []
      responses:
        '200': { description: OK }
    post:
      summary: Create employee
      security:
        - bearerAuth: []
      responses:
        '201': { description: Created }
  /api/employees/{id}:
    get:
      summary: Get employee
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /api/attendance/{employeeId}/checkin:
    post:
      summary: Employee check-in
      security:
        - bearerAuth: []
      parameters:
        - name: employeeId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lat: { type: number }
                lon: { type: number }
      responses:
        '200': { description: OK }
  /api/attendance/{employeeId}/checkout:
    post:
      summary: Employee check-out
      security:
        - bearerAuth: []
      parameters:
        - name: employeeId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lat: { type: number }
                lon: { type: number }
      responses:
        '200': { description: OK }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
